### ISSUE TITLE
Разногласия перевода и его стандартизация

### ISSUE THREAD

**Issue by mrmlnc** [mrmlnc/October-Russian-Language#3]
Пора бы обсудить предложенный мной вариант перевода нашей любимой CMS. Суть в том, что я не всегда могу уловить суть ключа, который оторван от контекста (не могу найти в CMS или нужно смоделировать определенную ситуацию). Именно поэтому я бы хотел обсудить с вами некоторые моменты.

Например, начнем с последнего нововведения - менеджера медиафайлов. Я старался переводить на основе WordPress и Windows, но:
- `folder` - Каталог, директория или папка?
- Некоторые ключи:
  - `return_to_parent` - Вернуться в родительскую папку? Вернуться в корневую папку?
  - `return_to_parent_label` - Подняться на уровень выше? Подняться наверх? Подняться вверх?
  - `last_modified` - Последнее изменение? Дата последнего изменения?
  - `move_destination` - Папка назначения? Целевая папка?

**Comment by sozonovalexey** [comment]
folder - папка
return_to_parent - Мне кажется, что тут надо смотреть контекст.
last_modified - Последнее изменение
move_destination - Папка назначения
